### ISSUE TITLE
Question about notification server in test directory

### ISSUE THREAD

**Issue by HenrikGr** [danibram/trustly-client#35]
Hi and thank you for this repo. I'm planning to use it but have a question about the notification server example.

In your code it looks like you are using a public method prepareNotificationResponse and not the "private" one called _prepareNotificationResponse.

Could not see a public method in the code and wonder if it is a spelling error?

**Comment by danibram** [comment]
Sorry, i think i didnt update the example, its hard for me because i havent keys for testing the server, and last year i updated hard the library. 
You should use this `createNotificationResponse` you can check the code here, also it calls to _prepareNotificationResponse if you check the source code below:

-> https://github.com/danibram/trustly-client/blob/master/src/lib/Client.ts#L125

**Comment by HenrikGr** [comment]
Thanks, I thought that too.

How would the code look like to receive notifications. What I'm curious about is the callback parameter in the createNofitification method.

Could you explain a little?

**Comment by HenrikGr** [comment]
Never mind, I could see it now, it is there if a do not want to use then and catch.
Thanks.

**Comment by danibram** [comment]
No sorry, you can use async/await over the promises, or write a little helper to do with callbacks, as you preffer
